# .github/labeler.yml
documentation:
  - '**/*.md'
  - '**/*.txt'

enhancement:
  - '**/*.py'
  - '**/*.ctri'
  - 'Makefile'

update/addition:
  - '**/*.py'
  - '**/*.txt'
  - '**/*.ctri'
  - 'Makefile'
  - '.gitignore'
  - '.gitattributes'
  - '.github/workflows/**/*.yml'
